//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyCat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuesDesc
    {
        public int QAID { get; set; }
        public string Order { get; set; }
        public int QID { get; set; }
    
        public virtual Quesion Quesion { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
    }
}
