//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyCat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseDetail
    {
        public int RID { get; set; }
        public int QID { get; set; }
        public string Answers { get; set; }
        public System.DateTime createtime { get; set; }
        public System.DateTime lastupdate { get; set; }
    
        public virtual Quesion Quesion { get; set; }
        public virtual Response Response { get; set; }
    }
}
