//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyCat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Response()
        {
            this.ResponseDetails = new HashSet<ResponseDetail>();
        }
    
        public int RID { get; set; }
        public int SID { get; set; }
        public int UserID { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime lastupdate { get; set; }
        public Nullable<bool> isFinished { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseDetail> ResponseDetails { get; set; }
    }
}
